// Demo fixture data for Fed Simulator MCP tutorial

export const demoWrestlers = [
  {
    name: "Stone Cold Steve Austin",
    desc: "The Texas Rattlesnake",
    alignment: "FACE",
    gender: "MALE",
    height: 188,
    weight: 252,
    billedFrom: "Victoria, Texas",
    finisher: "Stone Cold Stunner",
    points: 95,
    morale: 85,
    stamina: 80,
    popularity: 95,
    charisma: 90,
    damage: 5,
    cost: 100000,
    active: true,
    role: "DEFAULT",
  },
  {
    name: "The Rock",
    desc: "The People's Champion",
    alignment: "FACE",
    gender: "MALE", 
    height: 196,
    weight: 260,
    billedFrom: "Miami, Florida",
    finisher: "Rock Bottom",
    points: 98,
    morale: 90,
    stamina: 85,
    popularity: 99,
    charisma: 95,
    damage: 2,
    cost: 150000,
    active: true,
    role: "DEFAULT",
  },
  {
    name: "Triple H",
    desc: "The Game",
    alignment: "HEEL",
    gender: "MALE",
    height: 193,
    weight: 255,
    billedFrom: "Greenwich, Connecticut", 
    finisher: "Pedigree",
    points: 92,
    morale: 88,
    stamina: 82,
    popularity: 75,
    charisma: 85,
    damage: 8,
    cost: 90000,
    active: true,
    role: "DEFAULT",
  },
  {
    name: "The Undertaker",
    desc: "The Deadman",
    alignment: "FACE",
    gender: "MALE",
    height: 208,
    weight: 309,
    billedFrom: "Death Valley",
    finisher: "Tombstone Piledriver",
    points: 96,
    morale: 85,
    stamina: 75,
    popularity: 90,
    charisma: 95,
    damage: 10,
    cost: 120000,
    active: true,
    role: "GIANT",
  },
  {
    name: "Mick Foley",
    desc: "Mankind",
    alignment: "FACE", 
    gender: "MALE",
    height: 188,
    weight: 287,
    billedFrom: "Long Island, New York",
    finisher: "Mandible Claw",
    points: 88,
    morale: 90,
    stamina: 70,
    popularity: 85,
    charisma: 80,
    damage: 15,
    cost: 75000,
    active: true,
    role: "BRUISER",
  },
  {
    name: "Shawn Michaels",
    desc: "The Heartbreak Kid",
    alignment: "FACE",
    gender: "MALE",
    height: 183,
    weight: 225,
    billedFrom: "San Antonio, Texas",
    finisher: "Sweet Chin Music",
    points: 94,
    morale: 87,
    stamina: 85,
    popularity: 88,
    charisma: 92,
    damage: 5,
    cost: 95000,
    active: true,
    role: "CRUISER",
  },
  {
    name: "Kurt Angle",
    desc: "The Olympic Hero",
    alignment: "HEEL",
    gender: "MALE",
    height: 183,
    weight: 225,
    billedFrom: "Pittsburgh, Pennsylvania",
    finisher: "Angle Slam",
    points: 90,
    morale: 80,
    stamina: 88,
    popularity: 70,
    charisma: 75,
    damage: 8,
    cost: 80000,
    active: true,
    role: "FIGHTER",
  },
  {
    name: "Chris Jericho",
    desc: "Y2J",
    alignment: "HEEL",
    gender: "MALE",
    height: 183,
    weight: 226,
    billedFrom: "Winnipeg, Manitoba",
    finisher: "Walls of Jericho",
    points: 85,
    morale: 85,
    stamina: 80,
    popularity: 65,
    charisma: 88,
    damage: 5,
    cost: 70000,
    active: true,
    role: "CRUISER",
  },
  {
    name: "Eddie Guerrero",
    desc: "Latino Heat",
    alignment: "FACE",
    gender: "MALE",
    height: 173,
    weight: 228,
    billedFrom: "El Paso, Texas",
    finisher: "Frog Splash",
    points: 87,
    morale: 88,
    stamina: 85,
    popularity: 80,
    charisma: 85,
    damage: 3,
    cost: 65000,
    active: true,
    role: "CRUISER",
  },
  {
    name: "Rey Mysterio",
    desc: "The Ultimate Underdog",
    alignment: "FACE",
    gender: "MALE", 
    height: 168,
    weight: 175,
    billedFrom: "San Diego, California",
    finisher: "619",
    points: 82,
    morale: 85,
    stamina: 90,
    popularity: 85,
    charisma: 80,
    damage: 2,
    cost: 60000,
    active: true,
    role: "CRUISER",
  },
  // Female wrestlers
  {
    name: "Trish Stratus",
    desc: "The Queen of WWE",
    alignment: "FACE",
    gender: "FEMALE",
    height: 168,
    weight: 56,
    billedFrom: "Toronto, Ontario",
    finisher: "Stratusfaction",
    points: 88,
    morale: 85,
    stamina: 80,
    popularity: 90,
    charisma: 90,
    damage: 3,
    cost: 75000,
    active: true,
    role: "DEFAULT",
  },
  {
    name: "Lita",
    desc: "The Extreme Diva",
    alignment: "FACE",
    gender: "FEMALE",
    height: 165,
    weight: 59,
    billedFrom: "Sanford, North Carolina", 
    finisher: "Moonsault",
    points: 85,
    morale: 88,
    stamina: 85,
    popularity: 85,
    charisma: 82,
    damage: 5,
    cost: 70000,
    active: true,
    role: "CRUISER",
  },
];

export const demoBrands = [
  {
    name: "Monday Night RAW",
    desc: "The flagship show of sports entertainment",
    color: "#FF0000",
    backgroundColor: "#000000", 
    balance: 5000000,
    companyId: 1,
  },
  {
    name: "Friday Night SmackDown", 
    desc: "The blue brand",
    color: "#0000FF",
    backgroundColor: "#FFFFFF",
    balance: 4500000,
    companyId: 1,
  },
];

export const demoCompanies = [
  {
    name: "World Wrestling Entertainment",
    desc: "Sports entertainment empire",
    color: "#FFD700",
    backgroundColor: "#000000",
  },
];

export const demoVenues = [
  {
    name: "Madison Square Garden",
    desc: "The World's Most Famous Arena",
    capacity: 20000,
    location: "New York, NY",
    cost: 500000,
    revenueMultiplier: 2.0,
    timeZone: "America/New_York",
    setupTimeInDays: 1,
    historicalRating: 95,
    pyroRating: 8,
    lightingRating: 9,
    parkingRating: 7,
    color: "#FFD700",
    backgroundColor: "#000080",
  },
  {
    name: "Staples Center",
    desc: "Home of Champions",
    capacity: 18000,
    location: "Los Angeles, CA", 
    cost: 450000,
    revenueMultiplier: 1.8,
    timeZone: "America/Los_Angeles",
    setupTimeInDays: 1,
    historicalRating: 90,
    pyroRating: 9,
    lightingRating: 8,
    parkingRating: 8,
    color: "#800080",
    backgroundColor: "#FFD700",
  },
];